gmdc:
  redis:
    expiration: 300

mybatis:
  type-aliases-package: com.example.demo.dao
  mapper-locations: classpath*:*Mapper.xml, classpath*:/*Mapper.xml

#数据库,暂时没有集成连接池
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/localtest?autoReconnect=true&autoReconnectForPools=true&useUnicode=true&characterEncoding=UTF8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    #整合连接池
    type: com.alibaba.druid.pool.DruidDataSource
    redis:
        database: 0
        password:
        pool:
          max-active: 200
          max-wait: -1
          max-idle: 20
          min-idle: 0
        timeout: 0
  activiti:
    check-process-definitions: false
#设置日志级别,打印sql
logging:
    level:
        com:
            example:
                demo: DEBUG
    pattern:
        console: '%d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n'
        file: '%d{yyyy/MM/dd-HH:mm} [%thread] %-5level %logger- %msg%n'

#更改端口
server:
  port: 8089



































